apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-job
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
          - name: selenium-tests
            image: java-selenium-framework
            imagePullPolicy: Never
      restartPolicy: Never